name: s3-web-page
template: ../
# template: https://
kind: Stack
variables:
  region: eu-central-1
  name: arti-web-static-page
  organization: Shalb
---
name: health-check
template: ../health-check/
kind: Stack
variables:
  url: {{ output "s3-web-page.outputs.url" }}



